# Authentication Endpoints Contract
# Platform Gap Completion - FR-013, FR-014, FR-015

openapi: 3.1.0
info:
  title: Authentication API
  version: 1.0.0
  description: JWT-based authentication endpoints for AI Agent Platform

servers:
  - url: /api/auth

paths:
  /register:
    post:
      summary: Register new user
      operationId: registerUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          $ref: './error-response.yaml#/components/responses/BadRequest'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: './error-response.yaml#/components/schemas/ErrorResponse'

  /login:
    post:
      summary: Authenticate user
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: './error-response.yaml#/components/schemas/AuthenticationError'

  /refresh:
    post:
      summary: Refresh access token
      operationId: refreshToken
      tags:
        - Authentication
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          $ref: './error-response.yaml#/components/responses/Unauthorized'

  /logout:
    post:
      summary: Logout (revoke token)
      operationId: logoutUser
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout successful
        '401':
          $ref: './error-response.yaml#/components/responses/Unauthorized'

  /me:
    get:
      summary: Get current user profile
      operationId: getCurrentUser
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          $ref: './error-response.yaml#/components/responses/Unauthorized'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          maxLength: 255
          example: user@example.com
        password:
          type: string
          minLength: 8
          maxLength: 128
          description: "Min 8 chars, at least 1 uppercase, 1 lowercase, 1 digit"
          example: SecurePass123

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: SecurePass123

    RefreshRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          description: Refresh token from login/register response

    AuthResponse:
      type: object
      properties:
        access_token:
          type: string
          description: JWT access token (15 min expiry)
        refresh_token:
          type: string
          description: Refresh token (7 day expiry)
        token_type:
          type: string
          enum: [bearer]
          default: bearer
        expires_in:
          type: integer
          description: Access token expiry in seconds
          example: 900
        user:
          $ref: '#/components/schemas/UserProfile'

    UserProfile:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
